/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialoguer;

import java.awt.Toolkit;
import controle.Connexion.ControleConnexion;
import javax.swing.JOptionPane;



/**
 *
 * @author Miguel GUTIEREZ
 */
public class FenConnexion extends javax.swing.JFrame {

    /**
     * Creates new form FenConnexion
     */
    public FenConnexion() {
        initComponents();
        complementGUI();
    }
    
    private void complementGUI(){
        //Affiche le logo
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logo/Tholdisimplepetit.png")));
        //Affiche le nom
     setTitle("MEEC");
    }
    
    private boolean controle_connexion_Appel(){
        
        String leNom= jText_Nom.getText();
        boolean bControle = false;
        String leMotdePasse = String.valueOf(jPass_Mdp.getPassword());
        
        if(ControleConnexion.control(leNom, leMotdePasse)){
            
            bControle=true;
                    
        }else{
            JOptionPane.showMessageDialog(null,"Problème de connexion à la base de données\n\nVos nom et mot de passe peuvent être eronés", "ALERTE", JOptionPane.ERROR_MESSAGE);
        }
        
        return bControle;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab_Nom = new javax.swing.JLabel();
        jLab_Ecran = new javax.swing.JLabel();
        jLab_Mdp = new javax.swing.JLabel();
        jText_Nom = new javax.swing.JTextField();
        jLab_Param = new javax.swing.JLabel();
        jPass_Mdp = new javax.swing.JPasswordField();
        jBtn_Valider = new javax.swing.JButton();
        jBtn_Quit = new javax.swing.JButton();
        javax.swing.JLabel jLab_Minifond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 350));
        setPreferredSize(new java.awt.Dimension(500, 350));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Nom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLab_Nom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connexion/utilisateur.png"))); // NOI18N
        jLab_Nom.setText("Utilisateur");
        jLab_Nom.setToolTipText("");
        getContentPane().add(jLab_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLab_Ecran.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLab_Ecran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connexion/ecran.png"))); // NOI18N
        jLab_Ecran.setText("Connexion MEEC");
        jLab_Ecran.setToolTipText("");
        getContentPane().add(jLab_Ecran, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 280, 70));

        jLab_Mdp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLab_Mdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connexion/key.png"))); // NOI18N
        jLab_Mdp.setText("Mot de passe");
        jLab_Mdp.setToolTipText("");
        getContentPane().add(jLab_Mdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jText_Nom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jText_Nom.setText("gestion");
        jText_Nom.setToolTipText("");
        jText_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_NomActionPerformed(evt);
            }
        });
        getContentPane().add(jText_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 200, 30));

        jLab_Param.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLab_Param.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connexion/switch-on.png"))); // NOI18N
        jLab_Param.setText("Paramètres de connexion");
        getContentPane().add(jLab_Param, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jPass_Mdp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPass_Mdp.setText("azerty");
        jPass_Mdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPass_MdpActionPerformed(evt);
            }
        });
        getContentPane().add(jPass_Mdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 200, 30));

        jBtn_Valider.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBtn_Valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connexion/valider.png"))); // NOI18N
        jBtn_Valider.setMnemonic('V');
        jBtn_Valider.setText("Valider");
        jBtn_Valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_ValiderMouseClicked(evt);
            }
        });
        jBtn_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ValiderActionPerformed(evt);
            }
        });
        jBtn_Valider.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtn_ValiderKeyPressed(evt);
            }
        });
        getContentPane().add(jBtn_Valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));
        jBtn_Valider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jBtn_Quit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBtn_Quit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connexion/quitter.png"))); // NOI18N
        jBtn_Quit.setMnemonic('Q');
        jBtn_Quit.setText("Quitter");
        jBtn_Quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_QuitMouseClicked(evt);
            }
        });
        jBtn_Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_QuitActionPerformed(evt);
            }
        });
        jBtn_Quit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtn_QuitKeyPressed(evt);
            }
        });
        getContentPane().add(jBtn_Quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));
        jBtn_Quit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLab_Minifond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connexion/ban.png"))); // NOI18N
        getContentPane().add(jLab_Minifond, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 410, 190));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jText_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_NomActionPerformed

    private void jPass_MdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPass_MdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPass_MdpActionPerformed

    private void jBtn_ValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_ValiderMouseClicked
        if(controle_connexion_Appel()){
            MenuPrincipale laFenetre = new MenuPrincipale();
            laFenetre.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jBtn_ValiderMouseClicked

    private void jBtn_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ValiderActionPerformed
        if(controle_connexion_Appel()){
            MenuPrincipale laFenetre = new MenuPrincipale();
            laFenetre.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jBtn_ValiderActionPerformed

    private void jBtn_ValiderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtn_ValiderKeyPressed
        // 10 = Touche Entrée
        if(evt.getKeyCode()== 10){
        if(controle_connexion_Appel()){
            MenuPrincipale laFenetre = new MenuPrincipale();
            laFenetre.setVisible(true);
            dispose();
        }
        }
    }//GEN-LAST:event_jBtn_ValiderKeyPressed

    private void jBtn_QuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_QuitMouseClicked
          System.exit(0);
    }//GEN-LAST:event_jBtn_QuitMouseClicked

    private void jBtn_QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_QuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtn_QuitActionPerformed

    private void jBtn_QuitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtn_QuitKeyPressed
        if(evt.getKeyCode()== 10){
        System.exit(0);
        }
    }//GEN-LAST:event_jBtn_QuitKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Quit;
    private javax.swing.JButton jBtn_Valider;
    private javax.swing.JLabel jLab_Ecran;
    private javax.swing.JLabel jLab_Mdp;
    private javax.swing.JLabel jLab_Nom;
    private javax.swing.JLabel jLab_Param;
    private javax.swing.JPasswordField jPass_Mdp;
    private javax.swing.JTextField jText_Nom;
    // End of variables declaration//GEN-END:variables
}
