/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialoguer;

import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author jeanm
 */
public class MenuPrincipale extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipale
     */
    public MenuPrincipale() {
        initComponents();
        complementGUI();
    }
    private void complementGUI(){
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logo/Tholdisimplepetit.png")));
        setTitle("MEEC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab_Titre = new javax.swing.JLabel();
        jButtonRetour = new javax.swing.JButton();
        jBut_Quitter = new javax.swing.JButton();
        jBut_AjoutCont = new javax.swing.JButton();
        jBut_SuprCont = new javax.swing.JButton();
        jBut_ModifEtat = new javax.swing.JButton();
        jLab_Ajout = new javax.swing.JLabel();
        jBut_GestionElements = new javax.swing.JButton();
        jLab_ModifEtat = new javax.swing.JLabel();
        jLab_GestionElements = new javax.swing.JLabel();
        jLab_Suppr = new javax.swing.JLabel();
        jLab_Fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Titre.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLab_Titre.setForeground(new java.awt.Color(255, 255, 255));
        jLab_Titre.setText("MEEC");
        getContentPane().add(jLab_Titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 40));

        jButtonRetour.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRetour, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 90, 50));

        jBut_Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accueil/quitter1.png"))); // NOI18N
        jBut_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_QuitterActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_Quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 100, 50));

        jBut_AjoutCont.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jBut_AjoutCont.setText("Ajouter");
        jBut_AjoutCont.setToolTipText("");
        jBut_AjoutCont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBut_AjoutContMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBut_AjoutContMouseExited(evt);
            }
        });
        jBut_AjoutCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_AjoutContActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_AjoutCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 240, 40));

        jBut_SuprCont.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jBut_SuprCont.setText("Supprimer ");
        jBut_SuprCont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBut_SuprContMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBut_SuprContMouseExited(evt);
            }
        });
        jBut_SuprCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_SuprContActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_SuprCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 240, 40));

        jBut_ModifEtat.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jBut_ModifEtat.setText("Modifier un Etat");
        jBut_ModifEtat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBut_ModifEtatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBut_ModifEtatMouseExited(evt);
            }
        });
        jBut_ModifEtat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_ModifEtatActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_ModifEtat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 240, 40));

        jLab_Ajout.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLab_Ajout.setForeground(new java.awt.Color(255, 255, 255));
        jLab_Ajout.setText("Ajouter un conteneur");
        jLab_Ajout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLab_AjoutMouseEntered(evt);
            }
        });
        getContentPane().add(jLab_Ajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 310, -1));

        jBut_GestionElements.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jBut_GestionElements.setText("Gestion Elements");
        jBut_GestionElements.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBut_GestionElementsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBut_GestionElementsMouseExited(evt);
            }
        });
        jBut_GestionElements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_GestionElementsActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_GestionElements, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 240, 40));

        jLab_ModifEtat.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLab_ModifEtat.setForeground(new java.awt.Color(255, 255, 255));
        jLab_ModifEtat.setText("Modifier l'état d'un conteneur");
        getContentPane().add(jLab_ModifEtat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 450, 30));

        jLab_GestionElements.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLab_GestionElements.setForeground(new java.awt.Color(255, 255, 255));
        jLab_GestionElements.setText("Ajouter Supprimer Modifier les quais, allees, emplacements et positions");
        getContentPane().add(jLab_GestionElements, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 790, -1));

        jLab_Suppr.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLab_Suppr.setForeground(new java.awt.Color(255, 255, 255));
        jLab_Suppr.setText("Supprimer un conteneur");
        getContentPane().add(jLab_Suppr, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 240, 20));

        jLab_Fond.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLab_Fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fond/fond.jpg"))); // NOI18N
        jLab_Fond.setText("Mofier ");
        jLab_Fond.setToolTipText("");
        jLab_Fond.setMaximumSize(new java.awt.Dimension(870, 680));
        jLab_Fond.setMinimumSize(new java.awt.Dimension(870, 680));
        jLab_Fond.setPreferredSize(new java.awt.Dimension(870, 680));
        getContentPane().add(jLab_Fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_QuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBut_QuitterActionPerformed

    private void jBut_GestionElementsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBut_GestionElementsMouseEntered
        // TODO add your handling code here:
        jLab_GestionElements.setForeground(Color.BLACK);
    }//GEN-LAST:event_jBut_GestionElementsMouseEntered

    private void jBut_GestionElementsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBut_GestionElementsMouseExited
        // TODO add your handling code here:
        jLab_GestionElements.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBut_GestionElementsMouseExited

    private void jBut_GestionElementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_GestionElementsActionPerformed
    FenAjoutElements uneFenAjout = new FenAjoutElements();
    uneFenAjout.setVisible(true);
    dispose();
    }//GEN-LAST:event_jBut_GestionElementsActionPerformed

    private void jBut_AjoutContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_AjoutContActionPerformed
        // TODO add your handling code here:
        FenAjout uneFenAjout = new FenAjout();
    uneFenAjout.setVisible(true);
    dispose();
    }//GEN-LAST:event_jBut_AjoutContActionPerformed

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        MenuPrincipale uneFenetre = new MenuPrincipale();
        uneFenetre.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jBut_SuprContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_SuprContActionPerformed
          FENSuppr uneFENSuppr = new FENSuppr();
    uneFENSuppr.setVisible(true);
    dispose();
    }//GEN-LAST:event_jBut_SuprContActionPerformed

    private void jBut_ModifEtatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_ModifEtatActionPerformed
       FENModifEtat uneFENModifEtat = new FENModifEtat();
    uneFENModifEtat.setVisible(true);
    dispose();
    }//GEN-LAST:event_jBut_ModifEtatActionPerformed

    private void jBut_ModifEtatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBut_ModifEtatMouseEntered
       jLab_ModifEtat.setForeground(Color.BLACK);
    }//GEN-LAST:event_jBut_ModifEtatMouseEntered

    private void jBut_ModifEtatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBut_ModifEtatMouseExited
        jLab_ModifEtat.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBut_ModifEtatMouseExited

    private void jLab_AjoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLab_AjoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLab_AjoutMouseEntered

    private void jBut_AjoutContMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBut_AjoutContMouseEntered
         jLab_Ajout.setForeground(Color.BLACK);
    }//GEN-LAST:event_jBut_AjoutContMouseEntered

    private void jBut_AjoutContMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBut_AjoutContMouseExited
         jLab_Ajout.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBut_AjoutContMouseExited

    private void jBut_SuprContMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBut_SuprContMouseEntered
        jLab_Suppr.setForeground(Color.BLACK);
    }//GEN-LAST:event_jBut_SuprContMouseEntered

    private void jBut_SuprContMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBut_SuprContMouseExited
        jLab_Suppr.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBut_SuprContMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_AjoutCont;
    private javax.swing.JButton jBut_GestionElements;
    private javax.swing.JButton jBut_ModifEtat;
    private javax.swing.JButton jBut_Quitter;
    private javax.swing.JButton jBut_SuprCont;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JLabel jLab_Ajout;
    private javax.swing.JLabel jLab_Fond;
    private javax.swing.JLabel jLab_GestionElements;
    private javax.swing.JLabel jLab_ModifEtat;
    private javax.swing.JLabel jLab_Suppr;
    private javax.swing.JLabel jLab_Titre;
    // End of variables declaration//GEN-END:variables
}
